logging:
 level:
  org:
   springframework: DEBUG

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/batish_money_management?schema=SCHEMA
  username: paurush
  password: shashvat3
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate:
   ddl-auto: update
   show-sql: true
  properties:
   hibernate:
    format_sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
